---
- name: apt cache update & upgrade
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full

- name: install packages
  apt:
    name:
      - curl
      - git
      - gnupg2
      - xz-utils
    state: present
    cache_valid_time: 3600
    update_cache: true